###################################################################
###################################################################
##########                                               ##########
##########       The contents of this file solely        ##########
##########       create the GUI and GUI functions.       ##########
##########       The game process child is also          ##########
##########       forked within this file.                ##########
##########                                               ##########
###################################################################
###################################################################


from PyQt5 import QtCore, QtGui, QtWidgets
import blackjack
from blackjack_globals import Message
import multiprocessing as mp
#import RPi.GPIO as GPIO
import blackjack_GPIO as GPIO

# DIMENSIONS OF TOUCH DISPLAY
HEIGHT = 480
WIDTH = 800

# FONT SIZES
font10 = QtGui.QFont('Helvetica',10)
font12 = QtGui.QFont('Helvetica',12)
font14 = QtGui.QFont('Helvetica',14)
font16 = QtGui.QFont('Helvetica',16)
font18 = QtGui.QFont('Helvetica',18)
font20 = QtGui.QFont('Helvetica',20)
font30 = QtGui.QFont('Helvetica',30, QtGui.QFont.Bold)
font48 = QtGui.QFont('Helvetica',48)

# INITIAL SETTINGS
number_of_players = "0"
initial_amount = 0
game_mode = ""
user_input = ""

# GLOBAL QUEUES USED FOR MULTIPROCESSING INTERACTION
gui_to_bj_queue = mp.Queue()    # gui write, blackjack read
bj_to_gui_queue = mp.Queue()    # blackjack write, gui read

# GAME PROCESS IS CREATED, CHILD PROCESS TO BLACKJACK ALGORITHM IS FORKED
game_process = mp.Process(target=blackjack.blackjack_process, args=(gui_to_bj_queue, bj_to_gui_queue))


###################################################################
###################################################################
########                                                 ##########
########               MAIN WINDOW CLASS                 ##########
########                                                 ##########
########     This class creates/displays the first       ##########
########      GUI ("JACKBLACK" window) and allows        ##########
########      access to the next GUI ("SETTINGS").       ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_MainWindow(object):

    # SWITCH FROM MAIN WINDOW TO SETTINGS WINDOW
    def mainToSettings(self, current_w):
        temp_w = current_w
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SettingsWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        temp_w.hide()

    # STYLES/SETUP OF MAIN GUI
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(WIDTH, HEIGHT)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # push button styling/actions
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.mainToSettings(MainWindow))
        self.pushButton.setGeometry(240, 300, 310, 50)
        self.pushButton.setFont(font18)
        self.pushButton.setObjectName("pushButton")

        # JackBlack label styling
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(220, 200, 360, 70)
        self.label.setFont(font30)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        # autogenerated styling
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # AUTOGENERATED TRANSLATION FROM GUI TO PYTHON
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start Game"))
        self.label.setText(_translate("MainWindow", "JACKBLACK"))


###################################################################
###################################################################
########                                                 ##########
########             SETTINGS WINDOW CLASS               ##########
########                                                 ##########
########        This class creates the settings          ##########
########       GUI ("SETTINGS" window) and allows        ##########
########     access to the next GUI ("CONFIRM BOX").     ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_SettingsWindow(object):

    # SETTINGS OPTIONS/OPEN CONFIRM BOX
    def openWindow(self, settings_w):
        # storing input values for the settings
        number_of_players = self.numberOfPlayersComboBox.currentText()
        initial_amount = self.startingAmountSpinBox.value()
        game_mode = self.gameModeSelect1ComboBox.currentText()
        user_input = self.insert.value()

        #user_input = self.insert.value()

        # opening up the confirmation box with user-selected settings
        self.window = QtWidgets.QDialog()
        self.ui = Ui_confirm_dialogbox(number_of_players, initial_amount, game_mode, user_input)
        self.ui.setupUi(self.window, settings_w)

        # displaying the values onto confirmation box
        self.ui.confirm_list_widget.addItems(["Number of Players: " + number_of_players,
            "Starting Amount: " + str(initial_amount),
            "Game Mode: " + game_mode,
            "User Input: " + str(user_input)])
        self.window.show()

    def gameModeChanged(self, game_mode):
        if game_mode == "Winning Amount":
            self.insert = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=5000,
            minimum=0,
            value=1000,
            singleStep=100)
        elif game_mode == "Number of Wins":
            self.insert = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=50,
            minimum=0,
            value=10,
            singleStep=1)
        elif game_mode == "Total Games":
            self.insert = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=50,
            minimum=0,
            value=10,
            singleStep=1)
        elif game_mode == "Duration":
            self.insert = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=300,
            minimum=0,
            value=60,
            singleStep=5)
        else:
            pass


    # STYLES/SETUP OF SETTINGS GUI
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(WIDTH, HEIGHT)
        SettingsWindow.setFont(font12)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")

        # game play settings label styling
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(300, 50, 360, 70)
        self.label.setFont(font14)
        self.label.setObjectName("label")

        # creating form layout of widgets
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(180, 130, 500, 200)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        # creating/styling numPlayers widget
        self.numberOfPlayersLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.numberOfPlayersLabel.setObjectName("numberOfPlayersLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numberOfPlayersLabel)
        self.numberOfPlayersComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.numberOfPlayersComboBox.setObjectName("numberOfPlayersComboBox")
        self.numberOfPlayersComboBox.addItem("")
        self.numberOfPlayersComboBox.addItem("")
        self.numberOfPlayersComboBox.addItem("")
        self.numberOfPlayersComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numberOfPlayersComboBox)
        
        # creating/styling startingAmount widget
        self.startingAmountLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.startingAmountLabel.setObjectName("startingAmountLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.startingAmountLabel)
        self.startingAmountSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=5000,
            minimum=0,
            value=1000,
            singleStep=100)
        self.startingAmountSpinBox.setObjectName("startingAmountSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.startingAmountSpinBox)
        
        # creating/styling gameMode widget
        self.gameModeSelect1Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.gameModeSelect1Label.setObjectName("gameModeSelect1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gameModeSelect1Label)
        self.gameModeSelect1ComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.gameModeSelect1ComboBox.addItems(["Winning Amount", "Number of Wins", "Total Games", "Duration"])
        self.gameModeSelect1ComboBox.setObjectName("gameModeSelect1ComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gameModeSelect1ComboBox)
        
        # creating/styling userInput widget
        self.insertLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.insertLabel.setObjectName("insertLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.insertLabel)

        # change the user input field depending on game mode selection
        game_mode = self.gameModeSelect1ComboBox.currentText()
        self.insert = QtWidgets.QSpinBox(self.formLayoutWidget,
            maximum=5000,
            minimum=0,
            value=1000,
            singleStep=100)
        #self.insert = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.insert.setObjectName("insert")
        #self.gameModeSelect1ComboBox.currentTextChanged.connect(self.gameModeChanged)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.insert)
        
        # push button styling
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget, clicked=lambda: self.openWindow(SettingsWindow))
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        
        # autogenerated styling (may be able to remove?)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 38))
        self.menubar.setObjectName("menubar")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)
        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    # AUTOGENERATED TRANSLATION FROM GUI TO PYTHON
    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "MainWindow"))
        self.label.setText(_translate("SettingsWindow", "Game Play Settings"))
        self.numberOfPlayersLabel.setText(_translate("SettingsWindow", "Number of Players:"))
        self.numberOfPlayersComboBox.setItemText(0, _translate("SettingsWindow", "1"))
        self.numberOfPlayersComboBox.setItemText(1, _translate("SettingsWindow", "2"))
        self.numberOfPlayersComboBox.setItemText(2, _translate("SettingsWindow", "3"))
        self.numberOfPlayersComboBox.setItemText(3, _translate("SettingsWindow", "4"))
        self.startingAmountLabel.setText(_translate("SettingsWindow", "Starting Amount:"))
        self.gameModeSelect1Label.setText(_translate("SettingsWindow", "Game Mode:"))
        self.insertLabel.setText(_translate("SettingsWindow", "User Input:"))
        self.pushButton.setText(_translate("SettingsWindow", "CONTINUE"))


###################################################################
###################################################################
########                                                 ##########
########                CONFIRM BOX CLASS                ##########
########                                                 ##########
########      This class creates the Confirm Box         ##########
########     GUI ("CONFIRM BOX" window) and allows       ##########
########    access to the next GUI ("PLAYER READY").     ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_confirm_dialogbox(object):

    # INITIALIZING THE GAME SETTINGS FROM PREVIOUS GUI
    def __init__(self, number_of_players, initial_amount, game_mode, user_input):
        self.number_of_players = number_of_players
        self.initial_amount = initial_amount
        self.game_mode = game_mode
        self.user_input = user_input
    
    # UPON CONFIRM BUTTON PRESS: CLOSE CURRENT GUIS, OPEN PLAYER_READY GUI
    def confirm_connection(self, set_w):
        # need to open new window and hide settings window
        set_w.hide()
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Player_ReadyWindow(self.number_of_players, self.initial_amount, self.game_mode, self.user_input)
        self.ui.setupUi(self.window)
        self.window.show()

    # UPON CANCEL BUTTON PRESS: DO NOTHING
    def reject_connection(self):
        pass

    # STYLES/SETUP OF CONFIRM BOX GUI
    def setupUi(self, confirm_dialogbox, SettingsWindow):
        confirm_dialogbox.setObjectName("confirm_dialogbox")
        confirm_dialogbox.resize(WIDTH, HEIGHT)

        # button styles/configurations
        self.buttonBox = QtWidgets.QDialogButtonBox(confirm_dialogbox)
        self.buttonBox.setGeometry(180, 260, 500, 200)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(lambda: self.confirm_connection(SettingsWindow))
        self.buttonBox.rejected.connect(lambda: self.reject_connection())

        # confirm box geometry/layout
        self.widget = QtWidgets.QWidget(confirm_dialogbox)
        self.widget.setGeometry(180, 100, 500, 200)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # confirmation label text styles/layout
        self.confirm_label = QtWidgets.QLabel(self.widget)
        self.confirm_label.setFont(font10)
        self.confirm_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.verticalLayout.addWidget(self.confirm_label)
        self.confirm_list_widget = QtWidgets.QListWidget(self.widget)
        self.confirm_list_widget.setObjectName("confirm_list_widget")
        self.verticalLayout.addWidget(self.confirm_list_widget)

        # autogenerated styling
        self.retranslateUi(confirm_dialogbox)
        self.buttonBox.accepted.connect(confirm_dialogbox.accept)
        self.buttonBox.rejected.connect(confirm_dialogbox.reject)
        QtCore.QMetaObject.connectSlotsByName(confirm_dialogbox)

    # AUTOGENERATED TRANSLATION FROM GUI TO PYTHON
    def retranslateUi(self, confirm_dialogbox):
        _translate = QtCore.QCoreApplication.translate
        confirm_dialogbox.setWindowTitle(_translate("confirm_dialogbox", "Confirmation"))
        self.confirm_label.setText(_translate("confirm_dialogbox", "Are these configurations correct?"))


###################################################################
###################################################################
########                                                 ##########
########               PLAYER READY CLASS                ##########
########                                                 ##########
########      This class creates the Player Ready        ##########
########     GUI ("PLAYER READY" window) and allows      ##########
########    access to the next GUI ("PLAYER GAME").      ##########
########     This contains the game_process, which       ##########
########      starts the official blackjack game.        ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_Player_ReadyWindow(object):

    # INITIALIZES GAMEPLAY SETTINGS FROM PRIOR GUI
    def __init__(self, numPlayers, startingAmount, gameMode, userInput):
        self.numPlayers = numPlayers
        self.startingAmount = startingAmount
        self.gameMode = gameMode
        self.userInput = userInput
        self.player_cards = []
        self.bet = 0

    # UPON BET_IT BUTTON PRESS: CLEAR ALL WIDGETS ON THE SCREEN, STORE DESIRED BET FOR GAME
    def bet_it(self, p1_mw):
        # clearing all widgets (necessary to avoid errors)
        for i in reversed(range(self.formLayout.count())): 
            self.formLayout.itemAt(i).widget().setParent(None)

        # TODO: need to change this to be similar to below formatting (get rid of centralwidget, need formLayout)
        # set vertical box layout
        #self.centralwidget.setLayout(QtWidgets.QVBoxLayout())
        #self.betting_label = QtWidgets.QLabel("Betting for this round?")

        # bet label styles/layout
        self.betting_label = QtWidgets.QLabel(self.centralwidget)
        self.betting_label.setText("Betting for this round?")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.betting_label)
        self.betting_label.setGeometry(180, 100, 500, 200)
        self.betting_label.setFont(font16)
        self.betting_label.setAcceptDrops(False)
        self.betting_label.setAlignment(QtCore.Qt.AlignCenter)
        self.betting_label.setObjectName("betting_label")

        """
        # betting amount scroll bar
        self.scroll_bet = QtWidgets.QSpinBox(self.centralwidget,
            maximum=500,
            minimum=10,
            value=10,
            singleStep=10)
        self.scroll_bet.setGeometry(400, 100, 500, 200)
        self.scroll_bet.setFont(font16)
        self.scroll_bet.setObjectName("scroll_bet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.scroll_bet)
        """
        self.user_bet = QtWidgets.QLabel(self.centralwidget)
        self.user_bet.setGeometry(400, 100, 500, 200)
        self.user_bet.setFont(font16)
        self.user_bet.setText("10")
        self.user_bet.setObjectName("scroll_bet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.user_bet)

        not_ready = True
        
        while(not_ready):
            if GPIO.input(p1_hit):
                # increment betting
                current_bet = int(self.user_bet.text())
                self.user_bet.setText(str(current_bet+10))
            elif GPIO.input(p1_stand):
                # done betting, move onto next window
                not_ready = False
            elif GPIO.input(p1_double):
                # decrement betting
                current_bet = int(self.user_bet.text())
                self.user_bet.setText(str(current_bet-10))
            else:
                pass

        """        
        # ok button styles/layout
        self.ok_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openWindow(p1_mw))
        self.ok_pushButton.setText("OK")
        self.ok_pushButton.setGeometry(180, 170, 500, 200)
        self.ready_pushButton.setFont(font16)
        self.ready_pushButton.setObjectName("ok_pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.ok_pushButton)
        """
        self.openWindow(p1_mw)


    # START BLACKJACK GAME; OPEN GAME WINDOW
    def openWindow(self, main_w):
        # start official Blackjack game
        self.startBlackJack() 

        # checking IDs in message queue/grabbing message contents (player cards)
        # this needs to account for multiple rounds
        while(1):
            msg = bj_to_gui_queue.get()
            if msg.id == "player_cards":
                self.player_cards = msg.content
                break
            elif msg.id == "dealer_cards":
                self.dealer_cards = msg.content
            else:
                pass

        # open new game window
        temp_w = main_w
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GameWindow(self.numPlayers, self.startingAmount, self.gameMode, self.userInput, self.bet, self.player_cards)
        self.ui.setupUi(self.window)
        self.window.show()

        # displaying the betting amount
        #self.bet = self.scroll_bet.value()
        self.bet = int(self.user_bet.text())
        self.ui.current_bet_field.setPlainText(str(self.bet))
        self.ui.your_cards_left_field.setPlainText(str(self.player_cards[0]))
        self.ui.your_cards_right_field.setPlainText(str(self.player_cards[1]))
        #self.ui.dealer_left_field.setPlainText(str(self.dealer_cards[0]))
        #self.ui.dealer_right_field.setPlainText(str(self.dealer_cards[1]))

        # close current betting window
        temp_w.hide()

    # OFFICIALLY STARTS BLACKJACK GAME; GAME_PROCESS STARTED
    def startBlackJack(self):
        # game_process is started here
        game_process.start()

        # saving bet data from previous input
        #self.bet = self.scroll_bet.value()
        self.bet = int(self.user_bet.text())

        # creating/putting message to queue
        start_msg = Message("game_start", [self.numPlayers, self.startingAmount, self.bet, self.gameMode, self.userInput])
        gui_to_bj_queue.put(start_msg)

        # printing game_process pid (for debugging/killing process)
        game_process_pid = game_process.pid
        print("Game pid: ", game_process_pid)

    # STYLES/SETUP OF PLAYER_READY GUI
    def setupUi(self, Player_ReadyWindow):
        Player_ReadyWindow.setObjectName("Player_ReadyWindow")
        Player_ReadyWindow.resize(WIDTH, HEIGHT)
        self.centralwidget = QtWidgets.QWidget(Player_ReadyWindow)
        self.centralwidget.setObjectName("centralwidget")

        # making a form layout
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(150, 130, 500, 200)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        # player label styling
        self.player_label = QtWidgets.QLabel(self.centralwidget)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.player_label)
        self.player_label.setFont(font48)
        self.player_label.setAcceptDrops(False)
        self.player_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player_label.setObjectName("player_label")

        # ready_push button styling/layout
        self.ready_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.bet_it(Player_ReadyWindow))
        self.ready_pushButton.setGeometry(100, 160, 250, 61)
        self.ready_pushButton.setFont(font12)
        self.ready_pushButton.setObjectName("ready_pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.ready_pushButton)
        
        # autogenerated styling (might be able to remove?)
        Player_ReadyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Player_ReadyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 22))
        self.menubar.setObjectName("menubar")
        Player_ReadyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Player_ReadyWindow)
        self.statusbar.setObjectName("statusbar")
        Player_ReadyWindow.setStatusBar(self.statusbar)
        self.retranslateUi(Player_ReadyWindow)
        QtCore.QMetaObject.connectSlotsByName(Player_ReadyWindow)

    # AUTOGENERATED TRANSLATION FROM GUI TO PYTHON
    def retranslateUi(self, Player_ReadyWindow):
        _translate = QtCore.QCoreApplication.translate
        Player_ReadyWindow.setWindowTitle(_translate("Player_ReadyWindow", "Player 1"))
        self.player_label.setText(_translate("Player_ReadyWindow", "Player 1"))
        self.ready_pushButton.setText(_translate("Player_ReadyWindow", "PRESS HERE WHEN READY!"))


###################################################################
###################################################################
########                                                 ##########
########                NEXT ROUND CLASS                 ##########
########                                                 ##########
########      This class creates the NEXT ROUND          ##########
########     GUI and allows access to next round.        ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_confirm_round(object):

    """
    # INITIALIZING THE GAME SETTINGS FROM PREVIOUS GUI
    def __init__(self, number_of_players, initial_amount, game_mode, user_input):
        self.number_of_players = number_of_players
        self.initial_amount = initial_amount
        self.game_mode = game_mode
        self.user_input = user_input
    """
    
    # UPON CONFIRM BUTTON PRESS: CLOSE CURRENT GUIS, OPEN PLAYER_READY GUI
    def confirm_connection(self):
        # need to open new window and hide settings window
        #self.hide()
        pass

    # UPON CANCEL BUTTON PRESS: DO NOTHING
    def reject_connection(self):
        pass

    # STYLES/SETUP OF CONFIRM BOX GUI
    def setupUi(self, confirm_round):
        confirm_round.setObjectName("confirm_round")
        confirm_round.resize(WIDTH, HEIGHT)

        # button styles/configurations
        self.buttonBox = QtWidgets.QDialogButtonBox(confirm_round)
        self.buttonBox.setGeometry(180, 260, 500, 200)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(lambda: self.confirm_connection())
        self.buttonBox.rejected.connect(lambda: self.reject_connection())

        # confirm box geometry/layout
        self.widget = QtWidgets.QWidget(confirm_round)
        self.widget.setGeometry(180, 100, 500, 200)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # confirmation label text styles/layout
        self.confirm_label = QtWidgets.QLabel(self.widget)
        self.confirm_label.setFont(font10)
        self.confirm_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.verticalLayout.addWidget(self.confirm_label)
        self.confirm_list_widget = QtWidgets.QListWidget(self.widget)
        self.confirm_list_widget.setObjectName("confirm_list_widget")
        self.verticalLayout.addWidget(self.confirm_list_widget)

        # autogenerated styling
        self.retranslateUi(confirm_round)
        self.buttonBox.accepted.connect(confirm_round.accept)
        self.buttonBox.rejected.connect(confirm_round.reject)
        QtCore.QMetaObject.connectSlotsByName(confirm_round)

    # AUTOGENERATED TRANSLATION FROM GUI TO PYTHON
    def retranslateUi(self, confirm_round):
        _translate = QtCore.QCoreApplication.translate
        confirm_round.setWindowTitle(_translate("confirm_round", "Confirmation"))
        self.confirm_label.setText(_translate("confirm_round", "READY FOR NEXT ROUND?"))


###################################################################
###################################################################
########                                                 ##########
########                PLAYER GAME CLASS                ##########
########                                                 ##########
########      This class creates the Player Game         ##########
########     GUI ("PLAYER GAME" window) and allows       ##########
########    for full gameplay experience. Majority       ##########
########     of game mode checks and functionality       ##########
########             of GUI is located here.             ##########
########                                                 ##########
###################################################################
###################################################################

class Ui_GameWindow(object):

    # INITIALIZING GAME SETTINGS FROM PRIOR WINDOW
    def __init__(self, numPlayers, startingAmount, gameMode, userInput, bet, playerCards):
        self.numPlayers = numPlayers
        self.currentAmount = startingAmount
        self.gameMode = gameMode
        self.userInput = userInput
        self.bet = bet
        self.player_cards = playerCards
        self.double_button_clicked = False

        # TESTING THIS FUNCTION
    def open_next_round(self):
        # opening up the confirmation box with user-selected settings
        self.window = QtWidgets.QDialog()
        self.ui = Ui_confirm_round()
        self.ui.setupUi(self.window)
        self.window.show()

    def done_round(self):
        while(1):
            msg0 = bj_to_gui_queue.get()

            if msg0.id == "player_cards":
                self.player_cards = msg0.content
                self.your_cards_left_field.setPlainText(str(self.player_cards))
                self.your_cards_right_field.setPlainText(str(""))
                # reset the gui bet and starting amount here
                self.amount_left_label.setText("Amount Left: " + str(self.currentAmount))
                self.current_bet_field.setPlainText(str(self.bet))
            elif msg0.id == "dealer_cards":
                self.dealer_cards = msg0.content
                self.dealer_left_field.setPlainText(str(self.dealer_cards))
                self.dealer_right_field.setPlainText(str(""))
                break
            elif msg0.id == "GAME OVER!":
                self.your_cards_left_field.setPlainText(str("GAME OVER!!"))
                # FIX THIS ONE
                break
            else:
                pass

    # UPON DOUBLE BUTTON PRESSED; UPDATE BET VALUE
    # FIX END ROUND PART
    def double_it(self):
        self.double_button_clicked = True

        if self.double_button_clicked:
            #value = self.current_bet_field.toPlainText()
            #value = int(value) * 2
            # need to double the avlue in Marvin's code, then send the message here and set to value
            #self.current_bet_field.setPlainText(str(value))
            #self.bet = value
            # TODO: send message about updated bet to game
            msg = Message("double", self.bet)
            gui_to_bj_queue.put(msg)

            while(1):
                msg1 = bj_to_gui_queue.get()
                if msg1.id == "player_cards":
                    self.player_cards = msg1.content
                    self.your_cards_left_field.setPlainText(str(self.player_cards))
                    self.your_cards_right_field.setPlainText(str(""))
                elif msg1.id == "wallet":
                    self.currentAmount = msg1.content
                    self.amount_left_label.setText("Amount Left: " + str(self.currentAmount))
                elif msg1.id == "doubled":
                    value = msg1.content
                    #self.bet = value
                    self.current_bet_field.setPlainText(str(value))
                elif msg1.id == "done_round":
                    # need to go back and reset DOUBLE/STAND/HIT BUTTON functionality
                    self.double_button_clicked == False

                    # self.bet = bet (reset?)
                    self.open_next_round()
                    self.done_round()
                    break
                else:
                    pass
        else:
            pass
        

        #self.double_button_clicked = True

    # TODO
    # when "STAND" button is pressed, do nothing to current bet, do nothing to cards, reveal dealer cards
    def stand_it(self):
        # not being incremented properly for the total amount here
        msg = Message("stand", None)
        gui_to_bj_queue.put(msg)
        self.dealer_cards = []

        while(1):
            msg = bj_to_gui_queue.get()
            if msg.id == "dealer_cards":
                self.dealer_cards = msg.content
            elif msg.id == "wallet":
                self.currentAmount = msg.content
                self.amount_left_label.setText("Amount Left: " + str(self.currentAmount))
            elif msg.id == "done_round":
                self.open_next_round()
                self.done_round()
                break
            else:
                pass
        self.dealer_left_field.setPlainText(str(self.dealer_cards))
        self.dealer_right_field.setPlainText(str(""))

    # TODO
    # when "HIT" button is pressed, do nothing to current bet, add another card to player
    def hit_it(self):
        msg = Message("hit", None)
        gui_to_bj_queue.put(msg)

        while(1):
            msg = bj_to_gui_queue.get()
            if msg.id == "player_cards":
                self.player_cards = msg.content
                self.your_cards_left_field.setPlainText(str(self.player_cards))
                self.your_cards_right_field.setPlainText(str(""))
                break
            elif msg.id == "wallet":
                self.currentAmount = msg.content
                self.amount_left_label.setText("Amount Left: " + str(self.currentAmount))
                break
            elif msg.id == "done_round":
                self.done_round()
                break
            else:
                pass
        

    def exit_it(self):
        # TODO: fix this code for exit button
        result = "game_process" in globals()
        if result:
            game_process.terminate()
            game_process.join()
            # this will close the application, but prints out an event loop running error
            sys.exit(app.exec_())
        else:
            pass

    # setting up main window and components
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(WIDTH, HEIGHT)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(250, 280, 300, 150)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.your_cards_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.your_cards_layout.setContentsMargins(0, 0, 0, 0)
        self.your_cards_layout.setObjectName("your_cards_layout")

        self.your_cards_left_field = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget,
            readOnly=True)
        self.your_cards_left_field.setObjectName("your_cards_left_field")
        self.your_cards_left_field.setFont(font20)
        self.your_cards_layout.addWidget(self.your_cards_left_field)
        self.your_cards_right_field = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget,
            readOnly=True)
        self.your_cards_right_field.setObjectName("your_cards_right_field")
        self.your_cards_right_field.setFont(font20)
        self.your_cards_layout.addWidget(self.your_cards_right_field)

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(250, 30, 300, 150)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

        self.dealer_cards_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.dealer_cards_layout.setContentsMargins(0, 0, 0, 0)
        self.dealer_cards_layout.setObjectName("dealer_cards_layout")
        self.dealer_left_field = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2,
            readOnly=True)
        self.dealer_left_field.setObjectName("dealer_left_field")
        self.dealer_left_field.setFont(font20)
        self.dealer_cards_layout.addWidget(self.dealer_left_field)
        self.dealer_right_field = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2,
            readOnly=True)
        self.dealer_right_field.setObjectName("dealer_right_field")
        self.dealer_right_field.setFont(font20)
        self.dealer_cards_layout.addWidget(self.dealer_right_field)

        self.current_bet_field = QtWidgets.QPlainTextEdit(self.centralwidget,
            readOnly=True)
        self.current_bet_field.setFont(font20)
        self.current_bet_field.setGeometry(100, 310, 110, 110)
        self.current_bet_field.setObjectName("current_bet_field")

        # creating the amount left label
        self.amount_left_label = QtWidgets.QLabel(self.centralwidget)
        self.amount_left_label.setFont(font10)
        self.amount_left_label.setGeometry(600, 10, 300, 50)
        self.amount_left_label.setObjectName("amount_left_label")
        #self.amount_left_label.setText(str(self.currentAmount))

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(600, 280, 100, 150)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hit_button = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.hit_it())
        self.hit_button.setObjectName("hit_button")
        self.verticalLayout.addWidget(self.hit_button)
        self.double_button = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.double_it())
        self.double_button.setObjectName("double_button")
        self.verticalLayout.addWidget(self.double_button)
        self.stand_button = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.stand_it())
        self.stand_button.setObjectName("stand_button")
        self.verticalLayout.addWidget(self.stand_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.exit_it())
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)

        # change font size to be a lot bigger; maybe size 10?
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(355, 200, 110, 110)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(355, 140, 140, 110)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(110, 230, 110, 110)
        self.label_3.setObjectName("label_3")
        self.label.setFont(font10)
        self.label_2.setFont(font10)
        self.label_3.setFont(font10)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.amount_left_label.setText(_translate("MainWindow", "Amount Left: ") + str(self.currentAmount))
        self.hit_button.setText(_translate("MainWindow", "HIT"))
        self.double_button.setText(_translate("MainWindow", "DOUBLE"))
        self.stand_button.setText(_translate("MainWindow", "STAND"))
        self.exit_button.setText(_translate("MainWindow", "EXIT GAME"))
        self.label.setText(_translate("MainWindow", "Your Cards:"))
        self.label_2.setText(_translate("MainWindow", "Dealer\'s Cards:"))
        self.label_3.setText(_translate("MainWindow", "Current Bet:"))


if __name__ == "__main__":
    import sys
    initGPIO()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    #self.startBlackJack()
    #  This line will close the app, but I have it above in exit_it() function
    sys.exit(app.exec_())
