# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_window_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(18)
        Dialog.setFont(font)
        self.dialog_label = QtWidgets.QLabel(Dialog)
        self.dialog_label.setGeometry(QtCore.QRect(130, 100, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.dialog_label.setFont(font)
        self.dialog_label.setObjectName("dialog_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dialog_label.setText(_translate("Dialog", "Dialog Box"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
